[package]
name = "typhon"
version = "0.0.1"
edition = "2021"
authors = [ "Paul-Nicolas Madelaine <pnm@pnm.tf>" ]

[dependencies]
typhon-types.workspace = true
actix-cors.workspace = true
actix-files.workspace = true
actix-web.workspace = true
actix.workspace = true
age.workspace = true
async-stream.workspace = true
async-trait.workspace = true
clap.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
futures-core.workspace = true
futures.workspace = true
log.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
sha256.workspace = true
stderrlog.workspace = true
substring.workspace = true
tokio.workspace = true
